### ISSUE TITLE
Ошибка JSONDecodeError при запуске парсера

### ISSUE THREAD

**Issue by DoctorChe** [Shorstko/GibddStat#6]
Запускаю парсер со следующими параметрами:
`GibddStatParser.py --year 2018 --month 9 --regcode 1`
В итоге парсер начинает работу, но на каком-то этапе выдаёт ошибку:
```
Загрузчик данных по ДТП ГИБДД РФ
Обновление справочника отменено
Обрабатываются данные для Алтайский край (г.Барнаул) за 9-9.2018
144 ДТП для Алтайский край (г.Барнаул) за 9-9.2018
Обрабатываются данные для Алтайский край (Немецкий национальный район) за 9-9.20
18
1 ДТП для Алтайский край (Немецкий национальный район) за 9-9.2018
Обрабатываются данные для Алтайский край (Шипуновский район) за 9-9.2018
2 ДТП для Алтайский край (Шипуновский район) за 9-9.2018
Обрабатываются данные для Алтайский край (Чарышский район) за 9-9.2018
1 ДТП для Алтайский край (Чарышский район) за 9-9.2018
Обрабатываются данные для Алтайский край (Целинный район) за 9-9.2018
Traceback (most recent call last):
  File "GibddStatParser.py", line 313, in <module>
    main()
  File "GibddStatParser.py", line 302, in main
    getDTPInfo(data_root, year, months, regions, region_id=namespace.regcode)
  File "GibddStatParser.py", line 199, in getDTPInfo
    cards = getDTPData(region["id"], region["name"], district["id"], district["n
ame"], months, year)
  File "GibddStatParser.py", line 134, in getDTPData
    cards = json.loads(json.loads(r.content)["data"])["tab"]
  File "C:\Program1\WPy-3661\python-3.6.6.amd64\lib\json\__init__.py", line 354,
 in loads
    return _default_decoder.decode(s)
  File "C:\Program1\WPy-3661\python-3.6.6.amd64\lib\json\decoder.py", line 339,
in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program1\WPy-3661\python-3.6.6.amd64\lib\json\decoder.py", line 357,
in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Windows 8.1 x64 Python 3.6

**Comment by TalifaKumi** [comment]
аналогичный вопрос. отдельным постом.

**Comment by ya-mitra** [comment]
Добавьте это в скрипт:
```
if json.loads(r.content)["data"] == "":
    print("Response empty, skipped")
    break
```
![mf](https://user-images.githubusercontent.com/35805737/51174360-aa3a8b00-18c8-11e9-87d3-ba4528e4bf3f.jpg)

**Comment by Shorstko** [comment]
@Mitroright , благодарю за подсказку по строке в коде! исправила
